# Generated by Django 4.1.13 on 2024-06-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_alter_profile_aadharcard_no_alter_profile_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aadharcard_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='house_no',
        ),
        migrations.AddField(
            model_name='profile',
            name='society_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
